alias: null
batch_size: 64
context_size: 10
dataloader_kwargs: null
decoder_hidden_size: 25
decoder_layers: 2
drop_last_loader: false
early_stop_patience_steps: -1
encoder_activation: tanh
encoder_bias: true
encoder_dropout: 0.0
encoder_hidden_size: 25
encoder_n_layers: 2
exclude_insample_y: false
futr_exog_list:
- dayofweek
- monthofyear
- dia_das_maes
- dia_dos_pais
- dia_dos_namorados
- halloween
- black_friday
- natal
- copa_do_mundo
- eleicoes
- dia_do_trabalhador
- dia_de_finados
- confraternizacao_universal
- independencia_do_brasil
- nossa_senhora_aparecida
- proclamacao_da_republica
- sexta_feira_santa
- pascoa
- carnaval
- covid
- liquidacao
h: 365
h_train: 1
hist_exog_list:
- QLF
- ROL
- CPV
inference_input_size: null
inference_windows_batch_size: 1024
input_size: -1
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 1000
n_samples: 100
n_series: 1
num_lr_decays: -1
optimizer: null
optimizer_kwargs: null
random_seed: 1
recurrent: false
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 128
